package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import android.support.v7.widget.helper.ItemTouchHelper;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

/* JADX INFO: loaded from: classes.dex */
@cm
public final class aro {
    private static byte[] eW;
    private static final are<String> dr = are.a(0, "gads:sdk_core_experiment_id");

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final are<String> f4399a = are.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static final are<String> ds = are.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final are<Boolean> dt = are.a(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static final are<String> du = are.a(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final are<Boolean> dv = are.a(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static final are<String> dw = are.a(0, "gads:sdk_use_dynamic_module_experiment_id");

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    public static final are<Boolean> f4400b = are.a(0, "gads:sdk_crash_report_enabled", (Boolean) false);

    /* JADX INFO: renamed from: c, reason: collision with root package name */
    public static final are<Boolean> f4401c = are.a(0, "gads:report_dynamite_crash_in_background_thread", (Boolean) false);

    /* JADX INFO: renamed from: d, reason: collision with root package name */
    public static final are<Boolean> f4402d = are.a(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final are<String> e = are.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final are<Float> f = are.a(1, "gads:trapped_exception_sample_rate", 0.01f);
    public static final are<Boolean> g = are.a(0, "gads:block_autoclicks", (Boolean) false);
    private static final are<String> dx = are.a(0, "gads:block_autoclicks_experiment_id");
    private static final are<String> dy = are.a(0, "gads:spam_app_context:experiment_id");
    private static final are<Integer> dz = are.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final are<String> h = are.a(1, "gads:video_exo_player:version", "1");
    public static final are<Integer> i = are.a(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final are<Integer> j = are.a(1, "gads:video_exo_player:read_timeout", 8000);
    public static final are<Integer> k = are.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final are<Integer> l = are.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final are<Integer> m = are.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    private static final are<String> dA = are.a(0, "gads:video_stream_cache:experiment_id");
    public static final are<Integer> n = are.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final are<Integer> o = are.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final are<Integer> p = are.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final are<Long> q = are.a(1, "gads:video_stream_cache:limit_time_sec", 300L);
    public static final are<Long> r = are.a(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    public static final are<Integer> s = are.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final are<Boolean> t = are.a(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final are<String> u = are.a(1, "gads:video:metric_frame_hash_times", "");
    public static final are<Long> v = are.a(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    public static final are<Boolean> w = are.a(1, "gads:video:force_watermark", (Boolean) false);
    public static final are<Long> x = are.a(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    public static final are<Boolean> y = are.a(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final are<Integer> z = are.a(1, "gads:video:spinner:scale", 4);
    public static final are<Long> A = are.a(1, "gads:video:spinner:jank_threshold_ms", 50L);
    public static final are<Boolean> B = are.a(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final are<Boolean> C = are.a(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final are<Boolean> D = are.a(1, "gads:memory_bundle:runtime_info", (Boolean) true);
    public static final are<String> E = are.a(1, "gads:video:codec_query_mime_types", "");
    public static final are<Integer> F = are.a(1, "gads:video:codec_query_minimum_version", 16);
    private static final are<Boolean> dB = are.a(0, "gads:ad_id_app_context:enabled", (Boolean) false);
    private static final are<Float> dC = are.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static final are<String> dD = are.a(0, "gads:ad_id_app_context:experiment_id");
    private static final are<String> dE = are.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final are<Boolean> dF = are.a(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static final are<Float> dG = are.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static final are<Boolean> dH = are.a(0, "gads:ad_id_use_persistent_service:enabled", (Boolean) false);
    private static final are<Boolean> dI = are.a(0, "gads:ad_id:use_ipc:enabled", (Boolean) false);
    private static final are<String> dJ = are.b(0, "gads:looper_for_gms_client:experiment_id");
    public static final are<Boolean> G = are.a(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final are<Boolean> H = are.a(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    private static final are<Boolean> dK = are.a(0, "gads:sw_dynamite:enabled", (Boolean) true);
    public static final are<String> I = are.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final are<String> J = are.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final are<String> K = are.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final are<String> L = are.a(1, "gad:mraid:version", "2.0");
    public static final are<Boolean> M = are.a(1, "gads:mraid:unload", (Boolean) false);
    public static final are<Boolean> N = are.a(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final are<String> O = are.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final are<Boolean> P = are.a(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final are<Boolean> Q = are.a(0, "gads:enable_content_fetching", (Boolean) true);
    public static final are<Integer> R = are.a(0, "gads:content_length_weight", 1);
    public static final are<Integer> S = are.a(0, "gads:content_age_weight", 1);
    public static final are<Integer> T = are.a(0, "gads:min_content_len", 11);
    public static final are<Integer> U = are.a(0, "gads:fingerprint_number", 10);
    public static final are<Integer> V = are.a(0, "gads:sleep_sec", 10);
    public static final are<Boolean> W = are.a(1, "gads:enable_content_url_hash", (Boolean) true);
    public static final are<Integer> X = are.a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final are<Boolean> Y = are.a(1, "gads:enable_content_vertical_hash", (Boolean) true);
    public static final are<Integer> Z = are.a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final are<Integer> aa = are.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final are<String> ab = are.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final are<String> ac = are.a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final are<Boolean> ad = are.a(0, "gad:app_index_enabled", (Boolean) true);
    public static final are<Boolean> ae = are.a(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final are<Boolean> af = are.a(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final are<Long> ag = are.a(0, "gads:app_index:timeout_ms", 1000L);
    private static final are<String> dL = are.a(0, "gads:app_index:experiment_id");
    private static final are<String> dM = are.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final are<Boolean> ah = are.a(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final are<Boolean> ai = are.a(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final are<Boolean> aj = are.a(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    private static final are<String> dN = are.a(0, "gads:interstitial_follow_url:experiment_id");
    private static final are<Boolean> dO = are.a(0, "gads:analytics_enabled", (Boolean) true);
    public static final are<Boolean> ak = are.a(0, "gads:ad_key_enabled", (Boolean) false);
    public static final are<Boolean> al = are.a(1, "gads:sai:enabled", (Boolean) true);
    public static final are<Boolean> am = are.a(1, "gads:sai:banner_ad_enabled", (Boolean) true);
    public static final are<Boolean> an = are.a(1, "gads:sai:native_ad_enabled", (Boolean) true);
    public static final are<Boolean> ao = are.a(1, "gads:sai:interstitial_ad_enabled", (Boolean) true);
    public static final are<Boolean> ap = are.a(1, "gads:sai:rewardedvideo_ad_enabled", (Boolean) true);
    public static final are<String> aq = are.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final are<String> ar = are.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final are<Boolean> as = are.a(1, "gads:sai:click_gmsg_enabled", (Boolean) true);
    public static final are<Boolean> at = are.a(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final are<String> au = are.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final are<Long> av = are.a(1, "gads:sai:timeout_ms", -1L);
    public static final are<Integer> aw = are.a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final are<Boolean> ax = are.a(1, "gads:x_seconds_rewarded:enable", (Boolean) false);
    private static final are<Integer> dP = are.a(0, "gads:webview_cache_version", 0);
    public static final are<Boolean> ay = are.a(1, "gads:webview:ignore_over_scroll", (Boolean) true);
    public static final are<Boolean> az = are.a(0, "gads:corewebview:adwebview_factory:enable", (Boolean) false);
    public static final are<Boolean> aA = are.a(0, "gads:corewebview:javascript_engine", (Boolean) false);
    public static final are<Boolean> aB = are.a(1, "gad:webview:inject_scripts", (Boolean) false);
    public static final are<Boolean> aC = are.a(0, "gads:webview:permission:disabled", (Boolean) false);
    private static final are<String> dQ = are.b(0, "gads:pan:experiment_id");
    public static final are<Boolean> aD = are.a(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final are<Long> aE = are.a(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    public static final are<Boolean> aF = are.a(1, "gads:rewarded:ad_metadata_enabled", (Boolean) false);
    public static final are<Boolean> aG = are.a(1, "gads:app_activity_tracker:enabled", (Boolean) true);
    public static final are<Long> aH = are.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    public static final are<Long> aI = are.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final are<Boolean> aJ = are.a(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final are<Long> aK = are.a(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    public static final are<Boolean> aL = are.a(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final are<Boolean> aM = are.a(1, "gads:enable_ad_loader_manager", (Boolean) true);
    private static final are<Boolean> dR = are.a(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final are<Boolean> aN = are.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean) true);
    public static final are<Boolean> aO = are.a(1, "gads:ad_manager:admob_extra:new_bundle", (Boolean) true);
    public static final are<Long> aP = are.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    public static final are<Boolean> aQ = are.a(1, "gads:interstitial_ad_immersive_mode", (Boolean) true);
    public static final are<Boolean> aR = are.a(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final are<Boolean> aS = are.a(1, "gads:disabling_closable_area:enabled", (Boolean) false);
    private static final are<Boolean> dS = are.a(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static final are<String> dT = are.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final are<Integer> dU = are.a(1, "gads:banner_ad_pool:max_queues", 3);
    private static final are<Integer> dV = are.a(1, "gads:banner_ad_pool:max_pools", 3);
    public static final are<Boolean> aT = are.a(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final are<Boolean> aU = are.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final are<String> aV = are.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final are<String> aW = are.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final are<Integer> aX = are.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final are<Integer> aY = are.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final are<Integer> aZ = are.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final are<String> ba = are.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final are<Integer> bb = are.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final are<Integer> bc = are.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final are<Long> bd = are.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    public static final are<Long> be = are.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    public static final are<Float> bf = are.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final are<Float> bg = are.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final are<Boolean> bh = are.a(0, "gads:debug_logging_feature:enable", (Boolean) false);
    public static final are<Boolean> bi = are.a(0, "gads:debug_logging_feature:intercept_web_view", (Boolean) false);
    private static final are<Integer> dW = are.a(1, "gads:heap_wastage:bytes", 0);
    public static final are<String> bj = are.a(1, "gads:spherical_video:vertex_shader", "");
    public static final are<String> bk = are.a(1, "gads:spherical_video:fragment_shader", "");
    public static final are<Boolean> bl = are.a(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final are<Boolean> bm = are.a(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final are<Long> bn = are.a(1, "gads:position_watcher:throttle_ms", 200L);
    public static final are<Boolean> bo = are.a(1, "gads:include_lock_screen_apps_for_visibility", (Boolean) true);
    public static final are<Boolean> bp = are.a(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final are<Long> bq = are.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    public static final are<Boolean> br = are.a(1, "gads:gen204_signals:enabled", (Boolean) false);
    public static final are<Boolean> bs = are.a(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    private static final are<Boolean> dX = are.a(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static final are<Boolean> dY = are.a(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static final are<Boolean> dZ = are.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    private static final are<Boolean> ea = are.a(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final are<Boolean> bt = are.a(1, "gads:gmsg:disable_back_button:enabled", (Boolean) true);
    public static final are<Boolean> bu = are.a(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    private static final are<String> eb = are.a(0, "gads:gmsg:video_meta:experiment_id");
    private static final are<Long> ec = are.a(1, "gads:network:cache_prediction_duration_s", 300L);
    public static final are<Long> bv = are.a(1, "gads:network:network_prediction_timeout_ms", 2000L);
    public static final are<Boolean> bw = are.a(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final are<Boolean> bx = are.a(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final are<Boolean> by = are.a(1, "gads:bypass_adrequest_service_for_inlined_mediation", (Boolean) true);
    private static final are<Long> ed = are.a(1, "gads:rtb_signal_timeout_ms", 1000L);
    public static final are<Long> bz = are.a(0, "gads:resolve_future:default_timeout_ms", 30000L);
    public static final are<Long> bA = are.a(0, "gads:ad_loader:timeout_ms", 60000L);
    public static final are<Long> bB = are.a(0, "gads:rendering:timeout_ms", 60000L);
    public static final are<Boolean> bC = are.a(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final are<Long> bD = are.a(1, "gads:gestures:task_timeout", 2000L);
    public static final are<Boolean> bE = are.a(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final are<Boolean> bF = are.a(1, "gads:gestures:ans:enabled", (Boolean) false);
    public static final are<Boolean> bG = are.a(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final are<Boolean> bH = are.a(1, "gads:signal:app_permissions:disabled", (Boolean) false);
    public static final are<Boolean> bI = are.a(1, "gads:gestures:inthex:enabled", (Boolean) false);
    public static final are<Boolean> bJ = are.a(1, "gads:gestures:hpk:enabled", (Boolean) true);
    public static final are<String> bK = are.a(1, "gads:gestures:pk", "");
    public static final are<Boolean> bL = are.a(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final are<Boolean> bM = are.a(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final are<Boolean> bN = are.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final are<Boolean> bO = are.a(0, "gass:enabled", (Boolean) true);
    public static final are<Boolean> bP = are.a(0, "gass:enable_int_signal", (Boolean) true);
    public static final are<Boolean> bQ = are.a(0, "gass:enable_ad_attestation_signal", (Boolean) true);
    private static final are<Boolean> ee = are.a(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static final are<Boolean> ef = are.a(0, "gads:edu_device_helper:enabled", (Boolean) true);
    public static final are<Boolean> bR = are.a(0, "gads:support_screen_shot", (Boolean) true);
    public static final are<Boolean> bS = are.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    private static final are<String> eg = are.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static final are<String> eh = are.a(1, "gads:sdk_core_constants:experiment_id");
    public static final are<String> bT = are.a(1, "gads:sdk_core_constants:caps", "");
    public static final are<Long> bU = are.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final are<Boolean> bV = are.a(0, "gads:js_flags:mf", (Boolean) false);
    private static final are<Boolean> ei = are.a(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    public static final are<Boolean> bW = are.a(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final are<String> bX = are.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final are<String> ej = are.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final are<String> ek = are.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final are<String> bY = are.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static final are<String> el = are.a(1, "gads:singleton_webview_native:experiment_id");
    public static final are<Boolean> bZ = are.a(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final are<Boolean> ca = are.a(1, "gads:ignore_untrack_view_google_native", (Boolean) true);
    public static final are<Boolean> cb = are.a(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final are<Integer> cc = are.a(1, "gads:native_video_load_timeout", 10);
    public static final are<Integer> cd = are.a(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final are<String> ce = are.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final are<Boolean> cf = are.a(1, "gads:clamp_native_video_player_dimensions", (Boolean) true);
    public static final are<Boolean> cg = are.a(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final are<Boolean> ch = are.a(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final are<Boolean> ci = are.a(1, "gads:native:overlay_new_fix:enabled", (Boolean) true);
    public static final are<Boolean> cj = are.a(1, "gads:native:count_impression_for_assets", (Boolean) false);
    public static final are<Boolean> ck = are.a(1, "gads:native:custom_one_point_five_click:enable", (Boolean) true);
    public static final are<Boolean> cl = are.a(1, "gads:unified_native_ad:enable", (Boolean) true);
    public static final are<Boolean> cm = are.a(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final are<Boolean> cn = are.a(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final are<Long> co = are.a(0, "gads:method_tracing:duration_ms", 30000L);
    public static final are<Integer> cp = are.a(0, "gads:method_tracing:count", 5);
    public static final are<Integer> cq = are.a(0, "gads:method_tracing:filesize", 134217728);
    private static final are<Boolean> em = are.a(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static final are<String> en = are.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final are<Long> cr = are.a(1, "gads:auto_location_timeout", 2000L);
    private static final are<String> eo = are.b(1, "gads:auto_location_timeout:experiment_id");
    private static final are<Long> ep = are.a(1, "gads:auto_location_interval", -1L);
    private static final are<String> eq = are.b(1, "gads:auto_location_interval:experiment_id");
    public static final are<Boolean> cs = are.a(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    private static final are<String> er = are.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final are<Long> ct = are.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    private static final are<String> es = are.a(0, "gads:afs:csa:experiment_id");
    public static final are<String> cu = are.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final are<String> cv = are.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final are<String> cw = are.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final are<String> cx = are.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final are<String> cy = are.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final are<Long> cz = are.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    private static final are<Boolean> et = are.a(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    private static final are<Boolean> eu = are.a(1, "gads:parental_controls:send_from_client", (Boolean) true);
    private static final are<Boolean> ev = are.a(1, "gads:parental_controls:cache_results", (Boolean) true);
    public static final are<Long> cA = are.a(1, "gads:parental_controls:timeout", 2000L);
    private static final are<String> ew = are.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final are<Long> ex = are.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    public static final are<Boolean> cB = are.a(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final are<Boolean> cC = are.a(0, "gads:webview_cookie:enabled", (Boolean) true);
    private static final are<Integer> ey = are.a(1, "gads:cache:ad_request_timeout_millis", ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    private static final are<Integer> ez = are.a(1, "gads:cache:max_concurrent_downloads", 10);
    private static final are<Long> eA = are.a(1, "gads:cache:javascript_timeout_millis", 5000L);
    public static final are<Boolean> cD = are.a(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final are<Boolean> cE = are.a(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final are<Boolean> cF = are.a(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final are<Long> cG = are.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final are<Boolean> cH = are.a(1, "gads:cache:use_cache_data_source", (Boolean) false);
    private static final are<Boolean> eB = are.a(1, "gads:cache:connection_per_read", (Boolean) false);
    private static final are<Long> eC = are.a(1, "gads:cache:connection_timeout", 5000L);
    private static final are<Long> eD = are.a(1, "gads:cache:read_only_connection_timeout", 5000L);
    public static final are<Boolean> cI = are.a(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final are<String> cJ = are.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final are<Integer> cK = are.a(1, "gads:http_assets_cache:time_out", 100);
    public static final are<Boolean> cL = are.a(1, "gads:chrome_custom_tabs:enabled", (Boolean) true);
    public static final are<Boolean> cM = are.a(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final are<Boolean> cN = are.a(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final are<Boolean> cO = are.a(1, "gads:drx_in_app_preview:enabled", (Boolean) true);
    public static final are<Boolean> cP = are.a(1, "gads:drx_debug_signals:enabled", (Boolean) true);
    public static final are<Boolean> cQ = are.a(1, "gads:debug_hold_gesture:enabled", (Boolean) false);
    public static final are<Long> cR = are.a(1, "gads:debug_hold_gesture:time_millis", 2000L);
    public static final are<String> cS = are.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final are<String> cT = are.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final are<String> cU = are.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final are<String> cV = are.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final are<Integer> cW = are.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final are<Integer> cX = are.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final are<Boolean> cY = are.a(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final are<Boolean> cZ = are.a(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final are<Integer> da = are.a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final are<Boolean> db = are.a(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final are<Boolean> dc = are.a(1, "gads:clearcut_logging:write_to_file", (Boolean) false);
    public static final are<Boolean> dd = are.a(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);

    /* JADX INFO: renamed from: de, reason: collision with root package name */
    public static final are<Boolean> f4403de = are.a(0, "gad:force_dynamite_loading_enabled", (Boolean) false);
    public static final are<Integer> df = are.a(1, "gad:http_redirect_max_count:times", 8);
    public static final are<Boolean> dg = are.a(1, "gads:omid:enabled", (Boolean) false);
    private static final are<Boolean> eE = are.a(0, "gads:nonagon:red_button", (Boolean) false);
    private static final are<Boolean> eF = are.a(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static final are<String> eG = are.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final are<Boolean> eH = are.a(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static final are<String> eI = are.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final are<Boolean> eJ = are.a(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    private static final are<Boolean> eK = are.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    private static final are<String> eL = are.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final are<Boolean> eM = are.a(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static final are<String> eN = are.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final are<Boolean> dh = are.a(1, "gads:nonagon:banner:check_dp_size", (Boolean) false);
    private static final are<Boolean> eO = are.a(1, "gads:nonagon:service:enabled", (Boolean) false);
    private static final are<Boolean> eP = are.a(1, "gads:signals:ad_id_info:enabled", (Boolean) false);
    private static final are<Boolean> eQ = are.a(1, "gads:signals:app_index:enabled", (Boolean) false);
    private static final are<Boolean> eR = are.a(1, "gads:signals:cache:enabled", (Boolean) false);
    private static final are<Boolean> eS = are.a(1, "gads:signals:doritos:enabled", (Boolean) false);
    private static final are<Boolean> eT = are.a(1, "gads:signals:location:enabled", (Boolean) false);
    private static final are<Boolean> eU = are.a(1, "gads:signals:network_prediction:enabled", (Boolean) false);
    private static final are<Boolean> eV = are.a(1, "gads:signals:parental_control:enabled", (Boolean) false);
    public static final are<Long> di = are.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
    public static final are<String> dj = are.a(0, "gads:public_beta:traffic_multiplier", "1.0");
    public static final are<Boolean> dk = are.a(1, "gads:real_test_request:enabled", (Boolean) true);
    public static final are<Boolean> dl = are.a(1, "gads:real_test_request:render_webview_label", (Boolean) true);
    public static final are<Boolean> dm = are.a(1, "gads:real_test_request:render_native_label", (Boolean) true);
    public static final are<Integer> dn = are.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);

    /* JADX INFO: renamed from: do, reason: not valid java name */
    public static final are<Integer> f0do = are.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final are<Integer> dp = are.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final are<Integer> dq = are.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);

    public static List<String> a() {
        return aoo.e().a();
    }

    public static void a(Context context) {
        lp.a(context, new arp(context));
        int iIntValue = ((Integer) aoo.f().a(dW)).intValue();
        if (iIntValue <= 0 || eW != null) {
            return;
        }
        eW = new byte[iIntValue];
    }

    public static void a(Context context, int i2, JSONObject jSONObject) {
        aoo.d();
        SharedPreferences.Editor editorEdit = context.getSharedPreferences("google_ads_flags", 0).edit();
        aoo.e().a(editorEdit, 1, jSONObject);
        aoo.d();
        editorEdit.commit();
    }

    public static List<String> b() {
        return aoo.e().b();
    }
}
